const resObj = [
    {
      info: {
        id: "73579",
        name: "Hyderabad Bawarchi Dum Biryani",
        cloudinaryImageId: "scx9hi4ypwncigjnlrvw",
        locality: "Pothinamallayya Palem",
        areaName: "Madhurawada",
        costForTwo: "₹250 for two",
        cuisines: ["Biryani", "Chinese", "Tandoor", "South Indian"],
        avgRating: 4.1,
        parentId: "12374",
        avgRatingString: "4.1",
        totalRatingsString: "10K+",
        sla: {
          deliveryTime: 23,
          lastMileTravel: 2,
          serviceability: "SERVICEABLE",
          slaString: "23 mins",
          lastMileTravelString: "2.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-02 23:59:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "₹120 OFF",
          subHeader: "ABOVE ₹199",
          discountTag: "FLAT DEAL",
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-83d2d9a2-2118-4273-8ebd-7c6ea9656b66",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/hyderabad-bawarchi-dum-biryani-pothinamallayya-palem-madhurawada-vizag-73579",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "112148",
        name: "Mr.Little Idli",
        cloudinaryImageId: "ubi9rqbumwnjz63ua8qp",
        locality: "MVP Double road",
        areaName: "MVP Colony",
        costForTwo: "₹250 for two",
        cuisines: ["South Indian"],
        avgRating: 4.2,
        veg: true,
        parentId: "18047",
        avgRatingString: "4.2",
        totalRatingsString: "10K+",
        sla: {
          deliveryTime: 32,
          lastMileTravel: 11.8,
          serviceability: "SERVICEABLE",
          slaString: "32 mins",
          lastMileTravelString: "11.8 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-02 23:45:00",
          opened: true,
        },
        badges: {
          imageBadges: [
            {
              imageId: "v1695133679/badges/Pure_Veg111.png",
              description: "pureveg",
            },
          ],
        },
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {
              badgeObject: [
                {
                  attributes: {
                    description: "pureveg",
                    imageId: "v1695133679/badges/Pure_Veg111.png",
                  },
                },
              ],
            },
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "₹120 OFF",
          subHeader: "ABOVE ₹199",
          discountTag: "FLAT DEAL",
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-83d2d9a2-2118-4273-8ebd-7c6ea9656b66",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/mr-little-idli-mvp-double-road-mvp-colony-vizag-112148",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "90529",
        name: "Grill Citi - The Vizag Drive Inn",
        cloudinaryImageId: "qt15szvbtsqcf7da1qtd",
        locality: "Lawsons Bay Colony",
        areaName: "MVP Colony",
        costForTwo: "₹200 for two",
        cuisines: ["Lebanese", "Tandoor", "Kebabs"],
        avgRating: 4.4,
        parentId: "12831",
        avgRatingString: "4.4",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 35,
          lastMileTravel: 12.4,
          serviceability: "SERVICEABLE",
          slaString: "35 mins",
          lastMileTravelString: "12.4 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-02 23:45:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "₹120 OFF",
          subHeader: "ABOVE ₹199",
          discountTag: "FLAT DEAL",
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-83d2d9a2-2118-4273-8ebd-7c6ea9656b66",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/grill-citi-the-vizag-drive-inn-lawsons-bay-colony-mvp-colony-vizag-90529",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "60288",
        name: "Aruns Paradise Restaurant",
        cloudinaryImageId: "cm6qpyaze7meytpetwmy",
        locality: "MVP Colony",
        areaName: "Adarsh Nagar Road",
        costForTwo: "₹250 for two",
        cuisines: ["Biryani", "Chinese", "Tandoor", "Fast Food"],
        avgRating: 4.1,
        parentId: "13100",
        avgRatingString: "4.1",
        totalRatingsString: "10K+",
        sla: {
          deliveryTime: 30,
          lastMileTravel: 11.7,
          serviceability: "SERVICEABLE",
          slaString: "30 mins",
          lastMileTravelString: "11.7 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-02 23:59:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "₹120 OFF",
          subHeader: "ABOVE ₹199",
          discountTag: "FLAT DEAL",
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-83d2d9a2-2118-4273-8ebd-7c6ea9656b66",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/aruns-paradise-restaurant-mvp-colony-adarsh-nagar-road-vizag-60288",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "331267",
        name: "Home Food Co.",
        cloudinaryImageId: "281e84a0597840fe2805392e55ef5f4c",
        locality: "Sector 4",
        areaName: "MVP Colony",
        costForTwo: "₹200 for two",
        cuisines: ["Chinese", "Snacks", "Chaat", "Sweets", "Pizzas", "Burgers"],
        avgRating: 4.1,
        parentId: "96482",
        avgRatingString: "4.1",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 30,
          lastMileTravel: 10.8,
          serviceability: "SERVICEABLE",
          slaString: "30 mins",
          lastMileTravelString: "10.8 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-02 23:30:00",
          opened: true,
        },
        badges: {
          textExtendedBadges: [
            {
              iconId: "guiltfree/GF_Logo_android_3x",
              shortDescription: "options available",
              fontColor: "#7E808C",
            },
          ],
        },
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {
              badgeObject: [
                {
                  attributes: {
                    description: "",
                    fontColor: "#7E808C",
                    iconId: "guiltfree/GF_Logo_android_3x",
                    shortDescription: "options available",
                  },
                },
              ],
            },
          },
        },
        aggregatedDiscountInfoV3: {
          header: "₹120 OFF",
          subHeader: "ABOVE ₹199",
          discountTag: "FLAT DEAL",
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-83d2d9a2-2118-4273-8ebd-7c6ea9656b66",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/home-food-co-sector-4-mvp-colony-vizag-331267",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "419071",
        name: "CakeZone",
        cloudinaryImageId: "63970c0e51adaacf3abd27858df8fee8",
        locality: "GITAM COLLEGE POST",
        areaName: "Varahagiri Colony",
        costForTwo: "₹500 for two",
        cuisines: ["Bakery", "Desserts", "Sweets", "Ice Cream"],
        avgRating: 4.4,
        parentId: "7003",
        avgRatingString: "4.4",
        totalRatingsString: "1K+",
        sla: {
          deliveryTime: 28,
          lastMileTravel: 5.5,
          serviceability: "SERVICEABLE",
          slaString: "28 mins",
          lastMileTravelString: "5.5 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-02 23:59:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "₹120 OFF",
          subHeader: "ABOVE ₹199",
          discountTag: "FLAT DEAL",
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-83d2d9a2-2118-4273-8ebd-7c6ea9656b66",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/cakezone-gitam-college-post-varahagiri-colony-vizag-419071",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "642258",
        name: "Cakes Heaven",
        cloudinaryImageId: "01d818b25d0f008eefd86da28289880d",
        locality: "NGO Layout",
        areaName: "Madhurawada",
        costForTwo: "₹200 for two",
        cuisines: ["Bakery", "Desserts", "Sweets"],
        avgRating: 4,
        parentId: "55323",
        avgRatingString: "4.0",
        totalRatingsString: "50+",
        sla: {
          deliveryTime: 27,
          lastMileTravel: 0.8,
          serviceability: "SERVICEABLE",
          slaString: "27 mins",
          lastMileTravelString: "0.8 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-02 23:59:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "₹120 OFF",
          subHeader: "ABOVE ₹199",
          discountTag: "FLAT DEAL",
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-83d2d9a2-2118-4273-8ebd-7c6ea9656b66",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/cakes-heaven-ngo-layout-madhurawada-vizag-642258",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "80505",
        name: "SSM Cake World",
        cloudinaryImageId: "ff272hqy91xnaowo48fk",
        locality: "Ram Nagar",
        areaName: "Dwarakanagar",
        costForTwo: "₹150 for two",
        cuisines: ["Bakery", "Pizzas", "Chinese", "Fast Food"],
        avgRating: 4.1,
        parentId: "12944",
        avgRatingString: "4.1",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 36,
          lastMileTravel: 13.3,
          serviceability: "SERVICEABLE",
          slaString: "36 mins",
          lastMileTravelString: "13.3 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-02 23:59:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "₹120 OFF",
          subHeader: "ABOVE ₹199",
          discountTag: "FLAT DEAL",
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-83d2d9a2-2118-4273-8ebd-7c6ea9656b66",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/ssm-cake-world-ram-nagar-dwarakanagar-vizag-80505",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "412248",
        name: "Grand Sri Sai Ram Parlour",
        cloudinaryImageId: "sarb3i9a2vcnolu2vjpe",
        locality: "WS Approach Road",
        areaName: "Dwaraka Nagar",
        costForTwo: "₹150 for two",
        cuisines: ["South Indian"],
        avgRating: 4.1,
        veg: true,
        parentId: "315501",
        avgRatingString: "4.1",
        totalRatingsString: "1K+",
        sla: {
          deliveryTime: 36,
          lastMileTravel: 13.7,
          serviceability: "SERVICEABLE",
          slaString: "36 mins",
          lastMileTravelString: "13.7 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-02 23:35:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "₹120 OFF",
          subHeader: "ABOVE ₹199",
          discountTag: "FLAT DEAL",
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-83d2d9a2-2118-4273-8ebd-7c6ea9656b66",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/grand-sri-sai-ram-parlour-ws-approach-road-dwaraka-nagar-vizag-412248",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
  ];
export default resObj;